### ISSUE TITLE
closure for method breakpoint does not have access to Method

### ISSUE THREAD

**Issue by jetztgradnet** [kohsuke/youdebug#2]
The handler closure for MethodEntryEvent does not have access to the event itself, so it's diffcult to access to actual com.sun.jdi.Method object, which is required, e.g. to differ between multiple methods of the same name.

The handler closure is called here: 
See https://github.com/kohsuke/youdebug/blob/master/src/main/groovy/org/kohsuke/youdebug/VM.groovy#L311

**Comment by jetztgradnet** [comment]
There might be a way to access the Method object using `thread.frame(0).location().method()`, but that's a bit complicated in order to access the Method. So it would be nice to have a property `method` in `EventDelegate#getProperty(String)`

**Comment by kohsuke** [comment]
This is now fixed thanks to the pull request #5.
